name: Daily
on:
  push:
  schedule:
    - cron : '0 21 * * *'

jobs:
  collect:
    name: Collect Stocks Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.FULL_GITHUB_TOKEN }}
          repository: otomarukanta/stocks-collector
      - uses: actions/checkout@v2
        with:
          path: data
          token: ${{ secrets.FULL_GITHUB_TOKEN }}
          repository: otomarukanta/stocks-data
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install --dev
      - name: Collect
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          pipenv run python main.py
      - name: Commit data
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_GITHUB_TOKEN }}
        run: |
          cd data
          git config --local user.email "kanta208@gmail.com"
          git config --local user.name "otomarukanta"
          git add .
          git remote set-url --push origin https://otomarukanta:$GITHUB_TOKEN@github.com/otomarukanta/stocks-data
          git commit -m "Update Data" || true
          git push

  transform:
    name: Transform Stocks Data
    runs-on: ubuntu-latest
    needs: collect
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.FULL_GITHUB_TOKEN }}
          repository: otomarukanta/stocks-transformer
      - uses: actions/checkout@v2
        with:
          path: data
          token: ${{ secrets.FULL_GITHUB_TOKEN }}
          repository: otomarukanta/stocks-data
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install --dev
      - name: Collect
        run: |
          pipenv run python main.py
      - name: Commit data
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_GITHUB_TOKEN }}
        run: |
          cd data
          git config --local user.email "kanta208@gmail.com"
          git config --local user.name "otomarukanta"
          git add .
          git remote set-url --push origin https://otomarukanta:$GITHUB_TOKEN@github.com/otomarukanta/stocks-data
          git commit -m "Update Data" || true
          git push
